name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
        goarch:  ['amd64'] # ['amd64', 'arm64'] # arm64 will not work as long Github does not provide
        go: [ '1.19.2' ]
        continue-on-error: [true]

    runs-on: ${{ matrix.os }}
    env:
      mgoarch:  ${{ matrix.goos }}
      mgoos:  ${{ matrix.goarch }}

    steps:
     - uses: actions/checkout@v3

     - uses: actions/setup-go@v3
       with:
        go-version: ${{ matrix.go }}

     - name: Retrieve GOOS
       id: goos
       run: |
         echo "GOOS=$(go env GOOS)" >> $GITHUB_ENV

     - name: Install dependencies
       run: make
       env:
          GOARCH: ${{ matrix.goarch }}

     - name: Zip binary
       id: zip
       run: |
         zip mt_${{ env.GOOS }}_${{ matrix.goarch }}.zip mt

     - name: Release
       uses: softprops/action-gh-release@v1
       if: startsWith(github.ref, 'refs/tags/')
       with:
          files: |
            mt_${{ env.GOOS }}_${{ matrix.goarch }}.zip
